version: '3'
services:
  web:
    container_name: nignx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Configurações NGINX
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhosts/vhosts.conf:/etc/nginx/conf.d/vhosts.conf
      - ./nginx/proxy/upstream.conf:/etc/nginx/upstream.conf
      - ./nginx/logs:/etc/nginx/logs
      # - ./nginx/ssl/server.key:/etc/nginx/ssl/server.key
      # - ./nginx/ssl/server.crt:/etc/nginx/ssl/server.crt

      # Projetos
      # - ./projetos/primeiraAplicacaoDocker:/var/www/html/primeiraAplicacaoDocker
    network_mode: host